version: "3.8"
services:
  nemo:
    build:
      context: "./nemo"
      dockerfile: "Dockerfile-local"
    ports:
      - "8087:8087"

    depends_on:
      - "arangodb"
      - "text_analysis"
      - "initialisation_service"
    links:
      - "arangodb:arangodb"
      - "text_analysis:analysis"

  initialisation_service:
    build:
      context: "./initialisation-service"
      dockerfile: "Dockerfile-local"
    depends_on:
      - "arangodb"
      - "text_analysis"
    links:
      - "arangodb:arangodb"
      - "text_analysis:analysis"

  text_analysis:
    build: 
      context: "./text-analysis-service"
      dockerfile: "Dockerfile-local"
    ports:
      - "8092:8092"
    volumes:
      - ./text-analysis-service/models:/app/models

  arangodb:
    image: arangodb:latest
    container_name: "arangodb"
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
      - 8529:8529
    volumes:
      - ./data/arango/db:/var/lib/arangodb3
      - ./data/arango/app:/var/lib/arangodb3-apps
