version: "3.8"
services:
  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
      - 8529:8529
    volumes:
      - ./data/arango/db:/var/lib/arangodb3
      - ./data/arango/app:/var/lib/arangodb3-apps
  text_analysis:
    build: 
      context: "./text-analysis-service"
      dockerfile: "Dockerfile-local"
    ports:
      - "8092:8092"
    volumes:
      - ./text-analysis-service/models:/app/models
